Instance: careplan
InstanceOf: Bundle
Usage: #example
* type = #collection
* entry[0].fullUrl = "http://example.org/eLTSS/careplan1"
* entry[=].resource = careplan1
* entry[+].fullUrl = "http://example.org/Practitioner/planner1"
* entry[=].resource = planner1
* entry[+].fullUrl = "http://example.org/eLTSS/caremgr1"
* entry[=].resource = caremgr1
* entry[+].fullUrl = "http://example.org/Patient/patient1"
* entry[=].resource = patient1
* entry[+].fullUrl = "http://example.org/eLTSS/episode1"
* entry[=].resource = episode1
* entry[+].fullUrl = "http://example.org/eLTSS/careplan2"
* entry[=].resource = careplan2
* entry[+].fullUrl = "http://example.org/Goal/goal1"
* entry[=].resource = goal1
* entry[+].fullUrl = "http://example.org/Goal/goal2"
* entry[=].resource = goal2
* entry[+].fullUrl = "http://example.org/Condition/need1"
* entry[=].resource = need1
* entry[+].fullUrl = "http://example.org/Condition/need2"
* entry[=].resource = need2
* entry[+].fullUrl = "http://example.org/Condition/need3"
* entry[=].resource = need3
* entry[+].fullUrl = "http://example.org/eLTSS/provider1"
* entry[=].resource = provider1
* entry[+].fullUrl = "http://example.org/eLTSS/provider2"
* entry[=].resource = provider2
* entry[+].fullUrl = "http://example.org/eLTSS/provider3"
* entry[=].resource = provider3
* entry[+].fullUrl = "http://example.org/eLTSS/funding1"
* entry[=].resource = funding1
* entry[+].fullUrl = "http://example.org/eLTSS/relative1"
* entry[=].resource = daughter1
* entry[+].fullUrl = "http://example.org/eLTSS/guardian1"
* entry[=].resource = guardian1
* entry[+].fullUrl = "http://example.org/ServiceRequest/service1"
* entry[=].resource = service1
* entry[+].fullUrl = "http://example.org/ServiceRequest/service2"
* entry[=].resource = service2
* entry[+].fullUrl = "http://example.org/ServiceRequest/service3"
* entry[=].resource = service3
* entry[+].fullUrl = "http://example.org/Observation/strength1"
* entry[=].resource = strength1
* entry[+].fullUrl = "http://example.org/eLTSS/pref1"
* entry[=].resource = pref1
* entry[+].fullUrl = "http://example.org/RiskAssessment/risk1"
* entry[=].resource = risk1
* entry[+].fullUrl = "http://example.org/eLTSS/questionnaire1"
* entry[=].resource = questionnaire1
* entry[+].fullUrl = "http://example.org/QuestionnaireResponse/questionnaireresponse1"
* entry[=].resource = questionnaireresponse1
* entry[+].fullUrl = "http://example.org/Contract/contract1"
* entry[=].resource = contract1
* entry[+].fullUrl = "http://example.org/eLTSS/location1"
* entry[=].resource = location1
* entry[+].fullUrl = "http://example.org/eLTSS/coverage1"
* entry[=].resource = coverage1
* entry[+].fullUrl = "http://example.org/eLTSS/claim2"
* entry[=].resource = claim1