Instance: 2039212f3fa5406bb4ffd4a
InstanceOf: Bundle
Usage: #example
//Description: "Example of a Bundle with eLTSS data elements. Note: Review JSON and/or XML, as not all elements are rendered by the publisher in the narrative content"
//https://hl7.org/fhir/R4B/medicinalproductdefinition-operation-everything.html
* type = #searchset
* link.relation = #self
* link.url = "https://example.com/base/CarePlan/253/$all-eltss-careplan"

* entry[+].fullUrl = "https://hl7.org/fhir/Patient/patientBSJ1"
* entry[=].resource = patientBSJ1
* entry[+].fullUrl = "https://hl7.org/fhir/CarePlan/careplan1"
* entry[=].resource = careplan1
* entry[+].fullUrl = "https://hl7.org/fhir/Task/Task1"
* entry[=].resource = Task1
* entry[+].fullUrl = "https://hl7.org/fhir/Task/Task2"
* entry[=].resource = Task2
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/goal2"
* entry[=].resource = goal2
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/goal1"
* entry[=].resource = goal1
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/planner1"
* entry[=].resource = planner1
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/service2"
* entry[=].resource = service2
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/service3"
* entry[=].resource = service3
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/service4"
* entry[=].resource = service4
* entry[+].fullUrl = "https://hl7.org/fhir/RelatedPerson/son1"
* entry[=].resource = son1
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/strength1"
* entry[=].resource = strength1
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/strength2"
* entry[=].resource = strength2
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/caremgr1"
* entry[=].resource = caremgr1
* entry[+].fullUrl = "https://hl7.org/fhir/CarePlan/careplan2"
* entry[=].resource = careplan2
* entry[+].fullUrl = "https://hl7.org/fhir/Claim/claim1"
* entry[=].resource = claim1
* entry[+].fullUrl = "https://hl7.org/fhir/Claim/claim2"
* entry[=].resource = claim2
* entry[+].fullUrl = "https://hl7.org/fhir/Claim/claim3"
* entry[=].resource = claim3
* entry[+].fullUrl = "https://hl7.org/fhir/Contract/contract1"
* entry[=].resource = contract1
* entry[+].fullUrl = "https://hl7.org/fhir/Coverage/coverage1"
* entry[=].resource = coverage1
* entry[+].fullUrl = "https://hl7.org/fhir/EpisodeOfCare/episode1"
* entry[=].resource = episode1
* entry[+].fullUrl = "https://hl7.org/fhir/Organization/funding1"
* entry[=].resource = funding1
* entry[+].fullUrl = "https://hl7.org/fhir/RelatedPerson/guardian1"
* entry[=].resource = guardian1
* entry[+].fullUrl = "https://hl7.org/fhir/Location/location1"
* entry[=].resource = location1
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/need1"
* entry[=].resource = need1
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/need2"
* entry[=].resource = need2
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/need3"
* entry[=].resource = need3
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/need4"
* entry[=].resource = need4
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/pref1"
* entry[=].resource = pref1
* entry[+].fullUrl = "https://hl7.org/fhir/Organization/provider2a"
* entry[=].resource = provider2a
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/provider2b"
* entry[=].resource = provider2b
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/provider3"
* entry[=].resource = provider3
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/provider4"
* entry[=].resource = provider4
* entry[+].fullUrl = "https://hl7.org/fhir/PractitionerRole/PractitionerRole-1"
* entry[=].resource = PractitionerRole-1
* entry[+].fullUrl = "https://hl7.org/fhir/Location/communitysite"
* entry[=].resource = communitysite
* entry[+].fullUrl = "https://hl7.org/fhir/Questionnaire/questionnaire1"
* entry[=].resource = questionnaire1
* entry[+].fullUrl = "https://hl7.org/fhir/QuestionnaireResponse/questionnaireresponse1"
* entry[=].resource = questionnaireresponse1
* entry[+].fullUrl = "https://hl7.org/fhir/RiskAssessment/risk1"
* entry[=].resource = risk1
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/service1"
* entry[=].resource = service1
